//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace WeeksPlanning.HelperClasses
{
	/// <summary>Field Creation Class for entity PlanEntity</summary>
	public partial class PlanFields
	{
		/// <summary>Creates a new PlanEntity.CreatedByUserId field instance</summary>
		public static EntityField2 CreatedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.CreatedByUserId); }}
		/// <summary>Creates a new PlanEntity.DateCreatedUtc field instance</summary>
		public static EntityField2 DateCreatedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.DateCreatedUtc); }}
		/// <summary>Creates a new PlanEntity.DurationInWeeks field instance</summary>
		public static EntityField2 DurationInWeeks { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.DurationInWeeks); }}
		/// <summary>Creates a new PlanEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.Id); }}
		/// <summary>Creates a new PlanEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.IsActive); }}
		/// <summary>Creates a new PlanEntity.LastModifiedByUserId field instance</summary>
		public static EntityField2 LastModifiedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.LastModifiedByUserId); }}
		/// <summary>Creates a new PlanEntity.LastModifiedUtc field instance</summary>
		public static EntityField2 LastModifiedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.LastModifiedUtc); }}
		/// <summary>Creates a new PlanEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.Name); }}
		/// <summary>Creates a new PlanEntity.StartingDateUtc field instance</summary>
		public static EntityField2 StartingDateUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.StartingDateUtc); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.CreatedByUserId field instance</summary>
		public static EntityField2 CreatedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.CreatedByUserId); }}
		/// <summary>Creates a new UserEntity.DateCreatedUtc field instance</summary>
		public static EntityField2 DateCreatedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.DateCreatedUtc); }}
		/// <summary>Creates a new UserEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Email); }}
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.IsActive); }}
		/// <summary>Creates a new UserEntity.LastLoginDate field instance</summary>
		public static EntityField2 LastLoginDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.LastLoginDate); }}
		/// <summary>Creates a new UserEntity.LastModifiedByUserId field instance</summary>
		public static EntityField2 LastModifiedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.LastModifiedByUserId); }}
		/// <summary>Creates a new UserEntity.LastModifiedUtc field instance</summary>
		public static EntityField2 LastModifiedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.LastModifiedUtc); }}
		/// <summary>Creates a new UserEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Name); }}
		/// <summary>Creates a new UserEntity.Password field instance</summary>
		public static EntityField2 Password { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Password); }}
	}
	

}