//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using WeeksPlanning.FactoryClasses;
using WeeksPlanning.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace WeeksPlanning.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitPlanEntityInfo();
			InitUserEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits PlanEntity's info objects</summary>
		private void InitPlanEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PlanFieldIndex), "PlanEntity");
			this.AddElementFieldInfo("PlanEntity", "CreatedByUserId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)PlanFieldIndex.CreatedByUserId, 0, 0, 19);
			this.AddElementFieldInfo("PlanEntity", "DateCreatedUtc", typeof(System.DateTime), false, false, false, false,  (int)PlanFieldIndex.DateCreatedUtc, 0, 0, 0);
			this.AddElementFieldInfo("PlanEntity", "DurationInWeeks", typeof(System.Int16), false, false, false, false,  (int)PlanFieldIndex.DurationInWeeks, 0, 0, 5);
			this.AddElementFieldInfo("PlanEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)PlanFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("PlanEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)PlanFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("PlanEntity", "LastModifiedByUserId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)PlanFieldIndex.LastModifiedByUserId, 0, 0, 19);
			this.AddElementFieldInfo("PlanEntity", "LastModifiedUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)PlanFieldIndex.LastModifiedUtc, 0, 0, 0);
			this.AddElementFieldInfo("PlanEntity", "Name", typeof(System.String), false, false, false, false,  (int)PlanFieldIndex.Name, 100, 0, 0);
			this.AddElementFieldInfo("PlanEntity", "StartingDateUtc", typeof(System.DateTime), false, false, false, false,  (int)PlanFieldIndex.StartingDateUtc, 0, 0, 0);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "CreatedByUserId", typeof(Nullable<System.Int64>), false, false, false, true,  (int)UserFieldIndex.CreatedByUserId, 0, 0, 19);
			this.AddElementFieldInfo("UserEntity", "DateCreatedUtc", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.DateCreatedUtc, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Email", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Email, 100, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)UserFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("UserEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)UserFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "LastLoginDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.LastLoginDate, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "LastModifiedByUserId", typeof(Nullable<System.Int64>), false, false, false, true,  (int)UserFieldIndex.LastModifiedByUserId, 0, 0, 19);
			this.AddElementFieldInfo("UserEntity", "LastModifiedUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.LastModifiedUtc, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Name", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Name, 100, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Password", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Password, 100, 0, 0);
		}
	}
}