//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace View.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Plan'.</summary>
	[Serializable]
	[DataContract]
	public partial class PlanView
	{
		/// <summary>Gets or sets the CreatedByUser field. </summary>
		[DataMember]
		public PlanViewTypes.CreatedByUser CreatedByUser { get; set; }
		/// <summary>Gets or sets the CreatedByUserId field. Derived from Entity Model Field 'Plan.CreatedByUserId (FK)'</summary>
		[DataMember]
		public Nullable<System.Int64> CreatedByUserId { get; set; }
		/// <summary>Gets or sets the DateCreatedUtc field. Derived from Entity Model Field 'Plan.DateCreatedUtc'</summary>
		[DataMember]
		public System.DateTime DateCreatedUtc { get; set; }
		/// <summary>Gets or sets the DurationInWeeks field. Derived from Entity Model Field 'Plan.DurationInWeeks'</summary>
		[DataMember]
		public System.Int16 DurationInWeeks { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Plan.Id'</summary>
		[DataMember]
		public System.Int64 Id { get; set; }
		/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'Plan.IsActive'</summary>
		[DataMember]
		public System.Boolean IsActive { get; set; }
		/// <summary>Gets or sets the LastModifiedByUserId field. Derived from Entity Model Field 'Plan.LastModifiedByUserId (FK)'</summary>
		[DataMember]
		public Nullable<System.Int64> LastModifiedByUserId { get; set; }
		/// <summary>Gets or sets the LastModifiedUtc field. Derived from Entity Model Field 'Plan.LastModifiedUtc'</summary>
		[DataMember]
		public Nullable<System.DateTime> LastModifiedUtc { get; set; }
		/// <summary>Gets or sets the ModifiedByUser field. </summary>
		[DataMember]
		public PlanViewTypes.ModifiedByUser ModifiedByUser { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Plan.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
		/// <summary>Gets or sets the StartingDateUtc field. Derived from Entity Model Field 'Plan.StartingDateUtc'</summary>
		[DataMember]
		public System.DateTime StartingDateUtc { get; set; }
	}

	namespace PlanViewTypes
	{
		/// <summary> DTO class which is derived from the entity 'User (CreatedByUser)'.</summary>
		[Serializable]
		[DataContract]
		public partial class CreatedByUser
		{
			/// <summary>Gets or sets the DateCreatedUtc field. Derived from Entity Model Field 'User.DateCreatedUtc'</summary>
			[DataMember]
			public System.DateTime DateCreatedUtc { get; set; }
			/// <summary>Gets or sets the Email field. Derived from Entity Model Field 'User.Email'</summary>
			[DataMember]
			public System.String Email { get; set; }
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'User.Id'</summary>
			[DataMember]
			public System.Int64 Id { get; set; }
			/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'User.IsActive'</summary>
			[DataMember]
			public System.Boolean IsActive { get; set; }
			/// <summary>Gets or sets the LastLoginDate field. Derived from Entity Model Field 'User.LastLoginDate'</summary>
			[DataMember]
			public Nullable<System.DateTime> LastLoginDate { get; set; }
			/// <summary>Gets or sets the LastModifiedUtc field. Derived from Entity Model Field 'User.LastModifiedUtc'</summary>
			[DataMember]
			public Nullable<System.DateTime> LastModifiedUtc { get; set; }
			/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'User.Name'</summary>
			[DataMember]
			public System.String Name { get; set; }
			/// <summary>Gets or sets the Password field. Derived from Entity Model Field 'User.Password'</summary>
			[DataMember]
			public System.String Password { get; set; }
		}

		/// <summary> DTO class which is derived from the entity 'User (ModifiedByUser)'.</summary>
		[Serializable]
		[DataContract]
		public partial class ModifiedByUser
		{
			/// <summary>Gets or sets the DateCreatedUtc field. Derived from Entity Model Field 'User.DateCreatedUtc'</summary>
			[DataMember]
			public System.DateTime DateCreatedUtc { get; set; }
			/// <summary>Gets or sets the Email field. Derived from Entity Model Field 'User.Email'</summary>
			[DataMember]
			public System.String Email { get; set; }
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'User.Id'</summary>
			[DataMember]
			public System.Int64 Id { get; set; }
			/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'User.IsActive'</summary>
			[DataMember]
			public System.Boolean IsActive { get; set; }
			/// <summary>Gets or sets the LastLoginDate field. Derived from Entity Model Field 'User.LastLoginDate'</summary>
			[DataMember]
			public Nullable<System.DateTime> LastLoginDate { get; set; }
			/// <summary>Gets or sets the LastModifiedUtc field. Derived from Entity Model Field 'User.LastModifiedUtc'</summary>
			[DataMember]
			public Nullable<System.DateTime> LastModifiedUtc { get; set; }
			/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'User.Name'</summary>
			[DataMember]
			public System.String Name { get; set; }
			/// <summary>Gets or sets the Password field. Derived from Entity Model Field 'User.Password'</summary>
			[DataMember]
			public System.String Password { get; set; }
		}
	}

}




