name: .NET Core

on: [push]

jobs:
  build-backend:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore packages
      run: dotnet restore
      working-directory: ./WeeksPlanning
    - name: Build with dotnet
      run: dotnet build --no-restore --configuration Release
      working-directory: ./WeeksPlanning
      
  build-frontend:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          node-version: 12.x
      - name: Build frontend app with Node
        run: yarn
        working-directory: "./WeeksPlanning/WeeksPlanning.Api/Frontend"
      - name: Test frontend app with Jest
        run: yarn test
        working-directory: ./WeeksPlanning/WeeksPlanning.Api/Frontend
